name: Deploy to GitHub Pages
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build-and-deploy-gatsby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          persist-credentials: false

      - name: Install and Build 🚧
        run: |
          npm cache clean --force
          npm install
          npm run clean
          npm run build
        env:
          GATSBY_GOOGLE_FORM_ID: ${{ secrets.GATSBY_GOOGLE_FORM_ID }}
          NODE_OPTIONS: "--max-old-space-size=8192"
          GATSBY_CPU_COUNT: 2

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true

  deploy-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          persist-credentials: false

      - name: Install and Build 🚧
        run: |
          npm cache clean --force
          npm install
          npm run build
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SPREADSHEET_GID: ${{ secrets.GOOGLE_SPREADSHEET_GID }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD}}
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: werules/home-finder-private
          branch: gh-pages
          folder: scraper/build
          clean: true
          single-commit: true
